-- Opcjonalne obiekty raportowe i statystyki.

CREATE INDEX IDX_BANK_TX_TYPE_DATE
ON BANK_TRANSACTION(TRANSACTION_TYPE, TRANSACTION_DATE);

CREATE MATERIALIZED VIEW MV_TOP_CLIENTS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT a.CLIENT_ID,
       SUM(ABS(t.AMOUNT)) AS TOTAL_TURNOVER,
       COUNT(*) AS TRANSACTION_COUNT
  FROM BANK_TRANSACTION t
  JOIN ACCOUNT a ON a.ACCOUNT_ID = t.ACCOUNT_ID
 GROUP BY a.CLIENT_ID;

BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'ACCOUNT', CASCADE => TRUE);
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'BANK_TRANSACTION', CASCADE => TRUE);
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'BALANCE_HISTORY', CASCADE => TRUE);
END;
/
