-- Plik: orabank_performance.sql
-- Cel: Optymalizacja wydajności w OraBank

-- 1️⃣ Indeks złożony dla transakcji wg konta i daty
CREATE INDEX IDX_TRANSACTION_ACCOUNT_DATE_TYPE
ON TRANSACTION(ACCOUNT_ID, TRANSACTION_DATE, TRANSACTION_TYPE);

-- 2️⃣ Materialized view: top klienci dla szybkiego raportu
CREATE MATERIALIZED VIEW MV_TOP_CLIENTS
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
AS
SELECT CLIENT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTION
GROUP BY CLIENT_ID;

-- 3️⃣ Analiza statystyk
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS('BANK_CORE','ACCOUNT');
    DBMS_STATS.GATHER_TABLE_STATS('BANK_TX','TRANSACTION');
    DBMS_STATS.GATHER_TABLE_STATS('BANK_TX','BALANCE_HISTORY');
END;
/
