-- Plik: orabank_partitioning.sql
-- Cel: Partycjonowanie dużych tabel w OraBank

-- TRANSACTION – partycjonowanie według miesiąca TRANSACTION_DATE
CREATE TABLE TRANSACTION_PART (
    TRANSACTION_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID     NUMBER NOT NULL,
    TRANSACTION_DATE DATE DEFAULT SYSDATE,
    AMOUNT         NUMBER(15,2) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(30) NOT NULL,
    DESCRIPTION    VARCHAR2(200),
    BALANCE_AFTER  NUMBER(15,2)
)
PARTITION BY RANGE (TRANSACTION_DATE) (
    PARTITION TRANSACTION_202601 VALUES LESS THAN (TO_DATE('2026-02-01','YYYY-MM-DD')),
    PARTITION TRANSACTION_202602 VALUES LESS THAN (TO_DATE('2026-03-01','YYYY-MM-DD')),
    PARTITION TRANSACTION_202603 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD'))
    -- dodaj kolejne miesiące w razie potrzeby
);

-- BALANCE_HISTORY – partycjonowanie według CHANGE_DATE
CREATE TABLE BALANCE_HISTORY_PART (
    HISTORY_ID   NUMBER PRIMARY KEY,
    ACCOUNT_ID   NUMBER NOT NULL,
    BALANCE      NUMBER(15,2) NOT NULL,
    CHANGE_DATE  DATE DEFAULT SYSDATE
)
PARTITION BY RANGE (CHANGE_DATE) (
    PARTITION BALANCE_202601 VALUES LESS THAN (TO_DATE('2026-02-01','YYYY-MM-DD')),
    PARTITION BALANCE_202602 VALUES LESS THAN (TO_DATE('2026-03-01','YYYY-MM-DD')),
    PARTITION BALANCE_202603 VALUES LESS THAN (TO_DATE('2026-04-01','YYYY-MM-DD'))
    -- dodaj kolejne miesiące w razie potrzeby
);
