-- Uruchom jako administrator Oracle po instalacji schematu ORABANK.
-- Hasła są pobierane interaktywnie i nie są przechowywane w repozytorium.

SET VERIFY OFF
ACCEPT admin_password CHAR PROMPT 'Hasło dla ORABANK_ADMIN_USER: ' HIDE
ACCEPT teller_password CHAR PROMPT 'Hasło dla ORABANK_TELLER_USER: ' HIDE
ACCEPT auditor_password CHAR PROMPT 'Hasło dla ORABANK_AUDITOR_USER: ' HIDE

CREATE ROLE BANK_ADMIN;
CREATE ROLE BANK_TELLER;
CREATE ROLE BANK_AUDITOR;

GRANT SELECT, INSERT, UPDATE, DELETE ON ORABANK.CLIENT TO BANK_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORABANK.CLIENT_ADDRESS TO BANK_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORABANK.CLIENT_CONTACT TO BANK_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORABANK.ACCOUNT TO BANK_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORABANK.CARD TO BANK_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORABANK.LOAN TO BANK_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORABANK.LOAN_INSTALLMENT TO BANK_ADMIN;
GRANT SELECT ON ORABANK.AUDIT_LOG TO BANK_ADMIN;
GRANT EXECUTE ON ORABANK.ORABANK_ACCOUNT_PKG TO BANK_ADMIN;

GRANT SELECT ON ORABANK.CLIENT TO BANK_TELLER;
GRANT SELECT, INSERT, UPDATE ON ORABANK.ACCOUNT TO BANK_TELLER;
GRANT SELECT ON ORABANK.BANK_TRANSACTION TO BANK_TELLER;
GRANT SELECT ON ORABANK.TRANSFER TO BANK_TELLER;
GRANT SELECT ON ORABANK.CARD TO BANK_TELLER;
GRANT EXECUTE ON ORABANK.ORABANK_ACCOUNT_PKG TO BANK_TELLER;

GRANT SELECT ON ORABANK.ACCOUNT TO BANK_AUDITOR;
GRANT SELECT ON ORABANK.BANK_TRANSACTION TO BANK_AUDITOR;
GRANT SELECT ON ORABANK.TRANSFER TO BANK_AUDITOR;
GRANT SELECT ON ORABANK.BALANCE_HISTORY TO BANK_AUDITOR;
GRANT SELECT ON ORABANK.AUDIT_LOG TO BANK_AUDITOR;

CREATE OR REPLACE VIEW ORABANK.VW_DAILY_TRANSACTIONS AS
SELECT TRANSACTION_ID,
       ACCOUNT_ID,
       TRANSACTION_DATE,
       AMOUNT,
       TRANSACTION_TYPE,
       DESCRIPTION
  FROM ORABANK.BANK_TRANSACTION
 WHERE TRANSACTION_DATE >= TRUNC(SYSDATE)
   AND TRANSACTION_DATE < TRUNC(SYSDATE) + 1;

CREATE OR REPLACE VIEW ORABANK.VW_CLIENT_BALANCE AS
SELECT c.CLIENT_ID,
       c.FIRST_NAME,
       c.LAST_NAME,
       a.ACCOUNT_ID,
       a.ACCOUNT_NUMBER,
       a.BALANCE,
       a.CURRENCY_CODE
  FROM ORABANK.CLIENT c
  JOIN ORABANK.ACCOUNT a ON a.CLIENT_ID = c.CLIENT_ID;

CREATE OR REPLACE VIEW ORABANK.VW_TOP_CLIENTS AS
SELECT a.CLIENT_ID,
       SUM(ABS(t.AMOUNT)) AS TOTAL_TURNOVER
  FROM ORABANK.BANK_TRANSACTION t
  JOIN ORABANK.ACCOUNT a ON a.ACCOUNT_ID = t.ACCOUNT_ID
 GROUP BY a.CLIENT_ID;

GRANT SELECT ON ORABANK.VW_DAILY_TRANSACTIONS TO BANK_AUDITOR;
GRANT SELECT ON ORABANK.VW_CLIENT_BALANCE TO BANK_AUDITOR;
GRANT SELECT ON ORABANK.VW_TOP_CLIENTS TO BANK_AUDITOR;

CREATE USER ORABANK_ADMIN_USER IDENTIFIED BY "&admin_password" PASSWORD EXPIRE;
CREATE USER ORABANK_TELLER_USER IDENTIFIED BY "&teller_password" PASSWORD EXPIRE;
CREATE USER ORABANK_AUDITOR_USER IDENTIFIED BY "&auditor_password" PASSWORD EXPIRE;

GRANT CREATE SESSION, BANK_ADMIN TO ORABANK_ADMIN_USER;
GRANT CREATE SESSION, BANK_TELLER TO ORABANK_TELLER_USER;
GRANT CREATE SESSION, BANK_AUDITOR TO ORABANK_AUDITOR_USER;

UNDEFINE admin_password
UNDEFINE teller_password
UNDEFINE auditor_password
SET VERIFY ON
