-- Audyt zmian salda rachunku.

CREATE OR REPLACE TRIGGER TRG_ACCOUNT_BALANCE_AUDIT
AFTER UPDATE OF BALANCE ON ACCOUNT
FOR EACH ROW
WHEN (OLD.BALANCE <> NEW.BALANCE)
BEGIN
    INSERT INTO AUDIT_LOG (
        TABLE_NAME,
        RECORD_ID,
        OPERATION,
        USER_NAME,
        CHANGE_DATE
    ) VALUES (
        'ACCOUNT',
        :NEW.ACCOUNT_ID,
        'BALANCE_UPDATE',
        SYS_CONTEXT('USERENV', 'SESSION_USER'),
        SYSDATE
    );
END;
/

SHOW ERRORS TRIGGER TRG_ACCOUNT_BALANCE_AUDIT;
